### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by lsonnette** [ltauxe/PmagPy#22]
Hello,
I have just install PmagPy. I would like to launch QuickMagIC.py from the PmagPy Prompt but I get this message:

C:\Users\user\Documents>QuickMagIC.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\PmagPy\QuickMagIC.py", line 14, in <module>
    import pmag_basic_dialogs
  File "C:\Users\user\Documents\PmagPy\pmag_basic_dialogs.py", line 13, in <modu
le>
    import pmag_widgets as pw
  File "C:\Users\user\Documents\PmagPy\pmag_widgets.py", line 10, in <module>
    import controlled_vocabularies as vocabulary
  File "C:\Users\user\Documents\PmagPy\controlled_vocabularies.py", line 129, in
 <module>
    all_codes, code_types = get_meth_codes()
  File "C:\Users\user\Documents\PmagPy\controlled_vocabularies.py", line 21, in
get_meth_codes
    raw_codes = pd.io.json.read_json('http://api.earthref.org/MAGIC/method_codes
.json')
AttributeError: 'module' object has no attribute 'json'

I do not know how to fix this attribute error. Is anyone could help me?

**Comment by moonshoes87** [comment]
Thanks for reporting this!  There is a solution in the pipeline.  In the meantime, try updating the pandas package on your command line.  

In the PmagPy prompt, try:  enpkg pandas

You may be prompted for your Canopy/EPD credentials.  If you haven't registered with Enthought, you'll need to sign up at [the website](https://enthought.com/).  The full functionality is free with an academic email address, and there is also a lighter-weight version that is free for everyone.  

If you are prompted to update enpkg, go ahead and do so.  You will need to re-enter the "enpkg pandas" command.  Once you've finished the update, try running QuickMagIC again.  

If this doesn't work for you, there is still a solution coming soon!  Sorry for the inconvenience.

**Comment by lsonnette** [comment]
Thanks for your fast answer.
I have registered and got an academic licence with Enthought. I have also done the enpkg pandas, the enstaller was indeed out of date. I have re-enter the enpkg pandas. It has installed different egg. But unfortunately I got the same AttributeError when I launch QuickMagIC.py or Make_magic.py

**Comment by moonshoes87** [comment]
Sorry to hear that you haven't had success (yet)!  Thanks for your patience.  

It would be helpful for me if you could find out which version of pandas you have go into the PmagPy Command Prompt and type 'python'.  This should launch the python interpreter, which allows you to type pure python into the command prompt.  Try these commands:
>>>import pandas
>>>print pandas.__version__

If you could send me the output of those commands, it would be much appreciated and will allow me to better assist others.   

Onto actually fixing your problem, I have two possible solutions for you:
First, you can try downloading the most up to date version of [EPD here](https://store.enthought.com/repo/epd/installers/epd-7.5-2-win-x86_64.msi).  You may need to be signed in to your Enthought account to access this download.  This distribution may solve the problem and allow you to use all PmagPy functionality.  

Second option, you can try the new standalone [QuickMagIC for Windows](https://github.com/moonshoes87/PmagPy-Standalone-Windows/releases), which doesn't require a Python distribution at all.  However, this is still a pre-release: there are definitely some bugs.  If you do choose to use the standalone executable, please do report any problems you find.  

Let me know if you have success!

**Comment by lsonnette** [comment]
I have updated EPD. It works I can launch QuickMagIC.py (at least a new window opens).

Thanks for your help.

**Comment by moonshoes87** [comment]
Great!  I will update the documentation and close this issue.  Please let us know if you have any other problems.
