### ISSUE TITLE
marking good/bad measurements in Demag_GUI 

### ISSUE THREAD

**Issue by moonshoes87** [ltauxe/PmagPy#23]
The good/bad measurement highlighting behavior still seems a little unintuitive.  

First of all, it doesn’t seem like I can simply right click on a measurement — I actually have to select it with a left click and then right click.  Additionally, I was confused when I accidentally double-clicked on a measurement (trying to mark it as good/bad) and the whole fit was recalculated.  Last thing, measurements outside of the fit cannot be marked — is this the desired behavior?  

A possible UI solution: maybe we could introduce a 6th column in the measurements list with a checkbox the denotes a ‘bad’ measurement (or ‘good’).  This might be a slightly irritating to implement with wxPython, but I think it would make a lot of sense from a user perspective.

**Comment by Swanson-Hysell** [comment]
I agree that the right-click for "bad" isn't intuitive. The checkbox idea is a good one (potentially tricky to implement well?). I like the double click to make a fit functionality as it is quicker then dealing with drop-down windows. 






On Wednesday, Dec 16, 2015 at 10:24 AM, moonshoes87 <notifications@github.com>, wrote:

Closed #23.
